### PR TITLE
⬇️ Markdown Linting

### PR DESCRIPTION
**Pull request by lelia**
Given the majority of documentation content here is written in Markdown, we should be linting our `.md` files. 

# Changes

- Updates and expands the existing `.markdownlint.json` configuration
- Adds `avto-dev/markdown-lint` action to the existing `.github/lint.yml` workflow
- Fixes all current `markdownlint` violations under `/src/docs` and the repo root

### CODE REVIEW

**Comment by GaryPWhite** [comment]
you may want to rewind / rebase this -- I think it's based on your `renovate` branch and will conflict when we merge it (maybe)

**Comment by GaryPWhite** [comment]
either way it's hard to tell what's being edited here when those changes are also present :)

**Comment by lelia** [comment]
> you may want to rewind / rebase this -- I think it's based on your `renovate` branch and will conflict when we merge it (maybe)


Indeedy - hence the note: 

> ⚠️ Branched from https://github.com/wayfair-incubator/auxeng-docs/pull/27, which should be merged first.

If it's easier, let's just hold off on reviewing this until #27 is merged so I can update this branch from main.

**Comment by GaryPWhite** [comment]
i cant read ya that's ok

**Comment by lelia** [comment]
@GaryPWhite Should be ready for review now!

**Review by GaryPWhite — APPROVED** [review]

**Pull request merged**
